apiVersion: v1
kind: ConfigMap
metadata:
  name: atlantis-config
  namespace: default
data:
  config.yml: |
    allow-fork-prs: true
    atlantis-url: "https://62dc3799.ngrok.io"
    checkout-strategy: "merge"
  repos.yml: |
    repos:
      - id: github.com/jacobscunn07/AtlantisPOC
        apply_requirements: [mergeable]
        workflow: terragrunt
    workflows:
      terragrunt:
        plan:
          steps:
          - run: terragrunt plan -no-color -out $PLANFILE
        apply:
          steps:
          - run: terragrunt apply -no-color $PLANFILE
