apiVersion: v1
kind: ConfigMap
metadata:
  name: atlantis-config
  namespace: default
data:
  repos.yml: |
    repos:
      - id: github.com/jacobscunn07/AtlantisPOC
        apply_requirements: [approved]
        workflow: terragrunt
    workflows:
      terragrunt:
        plan:
          steps:
          - run: terragrunt plan-all -no-color -out $PLANFILE
        apply:
          steps:
          - run: terragrunt apply-all -no-color --terragrunt-non-interactive $PLANFILE
